services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
        - 80:80
        - 443:443
        develop:
            watch:
            # when the configuration file changes execute the action
            - path: ./nginx/default.conf
              action: sync+restart
              target: /etc/nginx/conf.d/default.conf